### ISSUE TITLE
Incorrect meta declaration

### ISSUE THREAD

**Issue by rengert** [PiranhaCMS/piranha.core.blog#1]
The meta view in the template is using incorrect declaration of the meta data. It is using key/value, but the correct way is either name/content or property/value depending on the meta data.

Reference for open graph (would be same for dublin core etc.)
http://ogp.me/

Summary
"Normal" meta like description, keywords etc with name="" content=""
"Special" meta like OpenGraph, Dublin Core etc. with property="" value=""

Example of the view:
meta name="description" content="@Model.MetaDescription"
meta property="og:description" value="@Model.MetaDescription"

**Comment by tidyui** [comment]
I would love a pull request if you already know how you think the `_Meta.cshtml` should be implemented! Since the template projects don't necessary follow the release cycle of the core NuGet packages there's no problem in pushing out an update before `5.1` is released.

**Comment by rengert** [comment]
i already tried before
git push -u origin bugfixes/meta-information

but i am not very fimilar with git. but i tried directly in vs and console. in the local branch everything is already committed.
permission denied is the only result i can see.

**Comment by tidyui** [comment]
Have you made a personal **fork** of the project to your user account, because you can't push directly to someone else's repository. The workflow is:

1. Create a fork of the project
2. Clone your personal fork of the project
3. Create a feature branch a push to your own fork
4. Create a **pull request** from your feature branch to master of the original project
5. The owner of the original project reviews and accept your changes.
6. Switch back to master of your fork
7. Sync the latest changes from the original repository to your fork

And yes, Git can be a bit of a monster when you first try to learn it :)

Best regards

**Comment by rengert** [comment]
Got, thank you! You can close this ticket, request has been sent.
